### ISSUE TITLE
[question] What is the random refer to in the diagrams

### ISSUE THREAD

**Issue by kirk86** [OATML/bdl-benchmarks#7]
I was wondering what does the random baseline refer to actually in tables/diagrams?
Lastly, any idea why are ensembles performing worse than mc-drop, I think in the paper of deep ensembles they showed that they performed better than mc-drop (plz correct me if I'm wrong)

Thanks!

**Comment by filangelos** [comment]
The "random" baseline refers to (uniformly) random filtering of test data points, while the rest of the methods filter based on their uncertainty (i.e., filter the most `k%` uncertain points, where `k` the different x-axis thresholds).

Please refer to our [paper](https://arxiv.org/abs/1912.10481) for a discussion on the performance of the different methods.

**Comment by kirk86** [comment]
Ευχαριστώ!
